Neos:
  ContentRepository:
    Search:
      openSearch:
        indexName: neoscr_testing
        log:
          backendOptions:
            fileBackend:
              logFileURL: '%FLOW_PATH_DATA%Logs/OpenSearch_Testing.log'
              severityThreshold: '%LOG_DEBUG%'
      realtimeIndexing:
        enabled: false

      defaultConfigurationPerNodeType:
        '*':
          indexed: true
        'Flowpack.OpenSearch.ContentRepositoryAdaptor:Type1':
          indexed: false

Flowpack:
  OpenSearch:
    ContentRepositoryAdaptor:
      command:
        useSubProcesses: false

