Neos:
  ContentRepository:
    Search:

      # API. If set to FALSE, only index the "live" workspace and not user workspaces.
      # If you only index the live workspace, Search will not work for your editors in the user workspaces.
      # Furthermore, if you heavily rely on Search for collecting content, this might be strange for editors to
      # work with -- as unpublished changes are not indexed right away.
      indexAllWorkspaces: true

      openSearch:

        # API. name of the OpenSearch index to use. Will create many indices prefixed by this indexName.
        indexName: neoscr

      defaultConfigurationPerType:

        string:
          openSearchMapping:
            type: keyword
            ignore_above: 8191

        boolean:
          openSearchMapping:
            type: boolean

        array:
          openSearchMapping:
            type: keyword
            ignore_above: 8191

        integer:
          openSearchMapping:
            type: integer

        DateTime:
          openSearchMapping:
            type: date
            format: 'date_time_no_millis'
          indexing: '${(value ? Date.format(value, "Y-m-d\TH:i:sP") : null)}'

        'Neos\Media\Domain\Model\Asset':
          openSearchMapping: '' # deliberately don't map or index this

        'array<Neos\Media\Domain\Model\Asset>':
          openSearchMapping: '' # deliberately don't map or index this

        'Neos\Media\Domain\Model\ImageInterface':
          openSearchMapping: '' # deliberately don't map or index this

        'references':
          openSearchMapping:
            type: keyword # an array of keywords, to be precise

        'reference':
          openSearchMapping:
            type: keyword
