Neos:
  ContentRepository:
    Search:
      openSearch:
        log:
          backendOptions:
            fileBackend:
              logFileURL: '%FLOW_PATH_DATA%Logs/OpenSearch_Development.log'
              severityThreshold: '%LOG_DEBUG%'
